name: Practice Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
          matrix:
             os: [ubuntu-latest, windows-latest, macos-latest]
    env:
        BASE_URL: ${{ vars.BASE_URL }}
        WORKERS: ${{ vars.WORKERS }}
        CREDENCIAL_EMAIL: ${{ secrets.CREDENCIAL_EMAIL }}
        CREDENCIAL_PASSWORD: ${{ secrets.CREDENCIAL_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Installing dependencies
      run: npm ci
    - name: Installing Playwright
      run: npx playwright install
    - name: Running Playwright Tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        overwrite: true
        name: playwright-report
        path: playwright-report/
        retention-days: 30
